---
title: "0731_reanalysis"
author: "Rentaro Mitsuyu"
date: "2024-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#rm(list =ls())
#install.packages("brms")
#tinytex::install_tinytex()
library(rstan) 
library(ggplot2)
library(rstudioapi)

rstan_options(auto_write=T)
options(mc.cores=parallel::detectCores())
```

資源1のグラフ
```{r}
Data <- read.csv("Data/0731_1.csv")    
Year <- Data$Year[!is.na(Data$Year)]  
Biomass <- Data$Biomass[!is.na(Data$Biomass)] 
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
Year.first <- min(Year)
Year.last <- max(Year)

data <- data.frame(Year=c(Year), Biomass=c(Biomass), Catch=c(Catch), CPUE=Data$CPUE*20)

q <- 0.05; K <- 3000
plot(data$Biomass, type="l")
plot(data$Catch, type="b")
plot(data$CPUE/q, data$Biomass)
plot(data$Catch/K, type="l")
plot(data$Catch/data$Biomass, type="l")


g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE*20"))+
  geom_point(aes(y=CPUE,col="CPUE*20"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE*20"="darkorange"),
                     name=NULL)

g1





g2 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Catch")+xlab("")+
  geom_bar(aes(y=Catch),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g2 <- ggplot(data=data, aes(x=Year)) +
  ylab("Catch") + 
  xlab("") +
  geom_bar(aes(y=Catch), stat="identity") +
  scale_x_continuous(expand = c(0, 0), limits=c(Year.first-0.5, Year.last+0.5),
                     breaks=c(seq(1975, 2024, 5))) 


g2


```

資源2のグラフ
```{r}
Data <- read.csv("Data/0731_2.csv")    
Year <- Data$Year[!is.na(Data$Year)]  
Biomass <- Data$Biomass[!is.na(Data$Biomass)] 
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
Year.first <- min(Year)
Year.last <- max(Year)

data <- data.frame(Year=c(Year), Biomass=c(Biomass), Catch=c(Catch), CPUE=Data$CPUE*20)



g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE*20"))+
  geom_point(aes(y=CPUE,col="CPUE*20"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE*20"="darkorange"),
                     name=NULL)

g1





g2 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Catch")+xlab("")+
  geom_bar(aes(y=Catch),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g2 <- ggplot(data=data, aes(x=Year)) +
  ylab("Catch") + 
  xlab("") +
  geom_bar(aes(y=Catch), stat="identity") +
  scale_x_continuous(expand = c(0, 0), limits=c(Year.first-0.5, Year.last+0.5),
                     breaks=c(seq(1975, 2024, 5))) 


g2


```

資源3のグラフ
```{r}
Data <- read.csv("Data/0731_3.csv")    
Year <- Data$Year[!is.na(Data$Year)]  
Biomass <- Data$Biomass[!is.na(Data$Biomass)] 
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
Year.first <- min(Year)
Year.last <- max(Year)

data <- data.frame(Year=c(Year), Biomass=c(Biomass), Catch=c(Catch), CPUE=Data$CPUE*20)



g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE*20"))+
  geom_point(aes(y=CPUE,col="CPUE*20"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE*20"="darkorange"),
                     name=NULL)

g1





g2 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Catch")+xlab("")+
  geom_bar(aes(y=Catch),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g2 <- ggplot(data=data, aes(x=Year)) +
  ylab("Catch") + 
  xlab("") +
  geom_bar(aes(y=Catch), stat="identity") +
  scale_x_continuous(expand = c(0, 0), limits=c(Year.first-0.5, Year.last+0.5),
                     breaks=c(seq(1975, 2024, 5))) 


g2


```

資源4のグラフ
```{r}
Data <- read.csv("Data/0731_4.csv")    
Year <- Data$Year[!is.na(Data$Year)]  
Biomass <- Data$Biomass[!is.na(Data$Biomass)] 
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
Year.first <- min(Year)
Year.last <- max(Year)

data <- data.frame(Year=c(Year), Biomass=c(Biomass), Catch=c(Catch), CPUE=Data$CPUE*20)


g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE*20"))+
  geom_point(aes(y=CPUE,col="CPUE*20"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE*20"="darkorange"),
                     name=NULL)

g1





g2 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Catch")+xlab("")+
  geom_bar(aes(y=Catch),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g2 <- ggplot(data=data, aes(x=Year)) +
  ylab("Catch") + 
  xlab("") +
  geom_bar(aes(y=Catch), stat="identity") +
  scale_x_continuous(expand = c(0, 0), limits=c(Year.first-0.5, Year.last+0.5),
                     breaks=c(seq(1975, 2024, 5))) 


g2


```

資源5のグラフ
```{r}
Data <- read.csv("Data/0731_5.csv")    
Year <- Data$Year[!is.na(Data$Year)]  
Biomass <- Data$Biomass[!is.na(Data$Biomass)] 
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
Year.first <- min(Year)
Year.last <- max(Year)

data <- data.frame(Year=c(Year), Biomass=c(Biomass), Catch=c(Catch), CPUE=Data$CPUE*20)


g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g1 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Biomass")+xlab("")+
  geom_bar(aes(y=Biomass),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE*20"))+
  geom_point(aes(y=CPUE,col="CPUE*20"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE*20"="darkorange"),
                     name=NULL)

g1





g2 <- ggplot(data=data,aes(x=Year))+
  ylab("Scaled abundance indices and Catch")+xlab("")+
  geom_bar(aes(y=Catch),stat="identity")+
  geom_line(aes(y=CPUE,col="CPUE"))+
  geom_point(aes(y=CPUE,col="CPUE"))+
  scale_x_continuous(expand = c(0,0), limits=c(Year.first-0.5,Year.last+0.5),
                     breaks=c(seq(1975,2024,5))) +
  scale_color_manual(values=c("CPUE"="darkorange"),
                     name=NULL)

g2 <- ggplot(data=data, aes(x=Year)) +
  ylab("Catch") + 
  xlab("") +
  geom_bar(aes(y=Catch), stat="identity") +
  scale_x_continuous(expand = c(0, 0), limits=c(Year.first-0.5, Year.last+0.5),
                     breaks=c(seq(1975, 2024, 5))) 


g2


```
各資源解析
1の資源量解析(ペラトムリンソン)
```{r}
#rm(list =ls())
Data <- read.csv("Data/0731_1.csv")  
Year <- Data$Year[!is.na(Data$Year)]  
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
TTYear  <- length(Year)                  
TTCatch <- length(Catch)       
TTCPUE <- length(CPUE) 

standata <- list(
  Year  = Year,
  Catch = Catch,
  CPUE = CPUE,
  TTYear = TTYear,
  TTCatch = TTCatch,
  TTCPUE = TTCPUE
  )

chain <- 4; iter <-50000; warmup = 25000; thin=10;(iter-warmup)/thin
#chain <- 1; iter <-20000; warmup = 5000; thin=10; (iter-warmup)/thin
#chain <- 2; iter <-1000; warmup = 500; thin=2; (iter-warmup)/thin

fit1z <- stan("0731_each.stan",  
               data=standata,
               chain=chain,iter=iter,warmup=warmup,thin=thin,seed=2024,
               control=list(adapt_delta=0.99,max_treedepth=15),
               init=function(){
                 list(r      = runif(1,0.5,1),
                      K      = runif(1,1000,4500),
                      D1     = runif(1,0.5,1),
                      shape     = runif(1,0.1,1),
                      tau    = runif(1,0.01,0.1),
                      sigmaCPUE  = runif(1,0.01,0.3),
                      q      = runif(1,0.04,0.06),
                      B  = runif(TTYear,100,4500))
               })
#save(fit1z, file="fit1z_0731.Rdata")
#summary(fit1z)
stan_dens(fit1z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"))
stan_dens(fit1z, pars=c("r"))
#stan_dens(fit1z, pars=c("shape"))
#traceplot(fit1z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"), inc_warmup = F)


fit1z_array <- as.array(fit1z)
# 各Chainのみのデータを抽出
fit1z_chain <- fit1z_array[, , 1]

plot(fit1z_chain1[,1], type="l")
plot(fit1z_chain2[,1], type="l")
plot(fit1z_chain3[,1], type="l")
plot(fit1z_chain4[,1], type="l")

hist(log(fit1z_chain[,]))

#pairs(fit, pars = c("r", "K", "D1", "tau", "sigmaCPUE", "q", "B"))
#library(shinystan)
#launch_shinystan(fit)

load("fit1z_0731.Rdata")
```

2の資源量解析(ペラトムリンソン)
```{r}
#rm(list =ls())
Data <- read.csv("Data/0731_2.csv")  
Year <- Data$Year[!is.na(Data$Year)]  
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
TTYear  <- length(Year)                  
TTCatch <- length(Catch)       
TTCPUE <- length(CPUE) 

standata <- list(
  Year  = Year,
  Catch = Catch,
  CPUE = CPUE,
  TTYear = TTYear,
  TTCatch = TTCatch,
  TTCPUE = TTCPUE
  )

chain <- 4; iter <-50000; warmup = 25000; thin=10;(iter-warmup)/thin
#chain <- 1; iter <-20000; warmup = 5000; thin=10; (iter-warmup)/thin
#chain <- 2; iter <-100; warmup = 10; thin=2; (iter-warmup)/thin

fit2z <- stan("0731_each.stan",  
               data=standata,
               chain=chain,iter=iter,warmup=warmup,thin=thin,seed=2024,
               control=list(adapt_delta=0.99,max_treedepth=15),
               init=function(){
                 list(r      = runif(1,0.5,1),
                      K      = runif(1,1000,4500),
                      D1     = runif(1,0.5,1),
                      shape     = runif(1,0.1,1),
                      tau    = runif(1,0.01,0.1),
                      sigmaCPUE  = runif(1,0.01,0.3),
                      q      = runif(1,0.04,0.06),
                      B  = runif(TTYear,100,4500))
               })
#save(fit2z, file="fit2z_0731.Rdata")
#summary(fit2z)
stan_dens(fit2z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"))
stan_dens(fit2z, pars=c("r"))
#stan_dens(fit1z, pars=c("shape"))
#traceplot(fit2z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"), inc_warmup = F)

#pairs(fit, pars = c("r", "K", "D1", "tau", "sigmaCPUE", "q", "B"))
#library(shinystan)
#launch_shinystan(fit)

load("fit2z_0731.Rdata")
```

3の資源量解析(ペラトムリンソン)
```{r}
#rm(list =ls())
Data <- read.csv("Data/0731_3.csv")  
Year <- Data$Year[!is.na(Data$Year)]  
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
TTYear  <- length(Year)                  
TTCatch <- length(Catch)       
TTCPUE <- length(CPUE) 

standata <- list(
  Year  = Year,
  Catch = Catch,
  CPUE = CPUE,
  TTYear = TTYear,
  TTCatch = TTCatch,
  TTCPUE = TTCPUE
  )

chain <- 4; iter <-50000; warmup = 25000; thin=10;(iter-warmup)/thin
#chain <- 1; iter <-20000; warmup = 5000; thin=10; (iter-warmup)/thin
#chain <- 2; iter <-100; warmup = 10; thin=2; (iter-warmup)/thin

fit3z <- stan("0731_each.stan",  
               data=standata,
               chain=chain,iter=iter,warmup=warmup,thin=thin,seed=2024,
               control=list(adapt_delta=0.99,max_treedepth=15),
               init=function(){
                 list(r      = runif(1,0.5,1),
                      K      = runif(1,1000,4500),
                      D1     = runif(1,0.5,1),
                      shape     = runif(1,0.1,1),
                      tau    = runif(1,0.01,0.1),
                      sigmaCPUE  = runif(1,0.01,0.3),
                      q      = runif(1,0.04,0.06),
                      B  = runif(TTYear,100,4500))
               })
#save(fit3z, file="fit3z_0731.Rdata")
#summary(fit3z)
stan_dens(fit3z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"))
stan_dens(fit3z, pars=c("r"))
#stan_dens(fit1z, pars=c("shape"))
#traceplot(fit3z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"), inc_warmup = F)

#pairs(fit, pars = c("r", "K", "D1", "tau", "sigmaCPUE", "q", "B"))
#library(shinystan)
#launch_shinystan(fit)

load("fit3z_0731.Rdata")
```

4の資源量解析(ペラトムリンソン)
```{r}
#rm(list =ls())
Data <- read.csv("Data/0731_4.csv")  
Year <- Data$Year[!is.na(Data$Year)]  
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
TTYear  <- length(Year)                  
TTCatch <- length(Catch)       
TTCPUE <- length(CPUE) 

standata <- list(
  Year  = Year,
  Catch = Catch,
  CPUE = CPUE,
  TTYear = TTYear,
  TTCatch = TTCatch,
  TTCPUE = TTCPUE
  )

chain <- 4; iter <-50000; warmup = 25000; thin=10;(iter-warmup)/thin
#chain <- 1; iter <-20000; warmup = 5000; thin=10; (iter-warmup)/thin
#chain <- 2; iter <-100; warmup = 10; thin=2; (iter-warmup)/thin

fit4z <- stan("0731_each.stan",  
               data=standata,
               chain=chain,iter=iter,warmup=warmup,thin=thin,seed=2024,
               control=list(adapt_delta=0.99,max_treedepth=15),
               init=function(){
                 list(r      = runif(1,0.5,1),
                      K      = runif(1,1000,4500),
                      D1     = runif(1,0.5,1),
                      shape     = runif(1,0.1,1),
                      tau    = runif(1,0.01,0.1),
                      sigmaCPUE  = runif(1,0.01,0.3),
                      q      = runif(1,0.04,0.06),
                      B  = runif(TTYear,100,4500))
               })
#save(fit4z, file="fit4z_0731.Rdata")
#summary(fit4z)
stan_dens(fit4z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"))
stan_dens(fit4z, pars=c("r"))
#stan_dens(fit1z, pars=c("shape"))
#traceplot(fit1z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"), inc_warmup = F)

#pairs(fit, pars = c("r", "K", "D1", "tau", "sigmaCPUE", "q", "B"))
#library(shinystan)
#launch_shinystan(fit)

load("fit4z_0731.Rdata")
```


5の資源量解析(ペラトムリンソン)
```{r}
#rm(list =ls())
Data <- read.csv("Data/0731_5.csv")  
Year <- Data$Year[!is.na(Data$Year)]  
Catch <- Data$Catch[!is.na(Data$Catch)]
CPUE <- Data$CPUE[!is.na(Data$CPUE)]

TT <- length(Year)
TTYear  <- length(Year)                  
TTCatch <- length(Catch)       
TTCPUE <- length(CPUE) 

standata <- list(
  Year  = Year,
  Catch = Catch,
  CPUE = CPUE,
  TTYear = TTYear,
  TTCatch = TTCatch,
  TTCPUE = TTCPUE
  )

chain <- 4; iter <-50000; warmup = 25000; thin=10;(iter-warmup)/thin
#chain <- 1; iter <-20000; warmup = 5000; thin=10; (iter-warmup)/thin
#chain <- 2; iter <-100; warmup = 10; thin=2; (iter-warmup)/thin

fit5z <- stan("0731_each.stan",  
               data=standata,
               chain=chain,iter=iter,warmup=warmup,thin=thin,seed=2024,
               control=list(adapt_delta=0.99,max_treedepth=15),
               init=function(){
                 list(r      = runif(1,0.5,1),
                      K      = runif(1,1000,4500),
                      D1     = runif(1,0.5,1),
                      shape     = runif(1,0.1,1),
                      tau    = runif(1,0.01,0.1),
                      sigmaCPUE  = runif(1,0.01,0.3),
                      q      = runif(1,0.04,0.06),
                      B  = runif(TTYear,100,4500))
               })
#save(fit5z, file="fit5z_0731.Rdata")
#summary(fit1z)
stan_dens(fit5z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"))
stan_dens(fit5z, pars=c("r"))


stan_dens(fit1z, pars=c("K"))
stan_dens(fit2z, pars=c("K"))
stan_dens(fit3z, pars=c("K"))
stan_dens(fit4z, pars=c("K"))
stan_dens(fit5z, pars=c("K"))


#stan_dens(fit1z, pars=c("shape"))
#traceplot(fit5z, pars=c("r", "K", "shape", "q", "D1", "tau", "sigmaCPUE"), inc_warmup = F)

#pairs(fit, pars = c("r", "K", "D1", "tau", "sigmaCPUE", "q", "B"))
#library(shinystan)
#launch_shinystan(fit)

load("fit5z_0731.Rdata")
```

階層ベイズモデル
ペラトムリンソンを仮定。rとzを階層構造に。
```{r}
#rm(list =ls())
Data_1 <- read.csv("Data/0731_1.csv")  
Year_1 <- Data_1$Year[!is.na(Data_1$Year)]  
Catch_1 <- Data_1$Catch[!is.na(Data_1$Catch)]
CPUE_1 <- Data_1$CPUE[!is.na(Data_1$CPUE)]

Data_2 <- read.csv("Data/0731_2.csv")  
Year_2 <- Data_2$Year[!is.na(Data_2$Year)]  
Catch_2 <- Data_2$Catch[!is.na(Data_2$Catch)]
CPUE_2 <- Data_2$CPUE[!is.na(Data_2$CPUE)]

Data_3 <- read.csv("Data/0731_3.csv")  
Year_3 <- Data_3$Year[!is.na(Data_3$Year)]  
Catch_3 <- Data_3$Catch[!is.na(Data_3$Catch)]
CPUE_3 <- Data_3$CPUE[!is.na(Data_3$CPUE)]

Data_4 <- read.csv("Data/0731_4.csv")  
Year_4 <- Data_4$Year[!is.na(Data_4$Year)]  
Catch_4 <- Data_4$Catch[!is.na(Data_4$Catch)]
CPUE_4 <- Data_4$CPUE[!is.na(Data_4$CPUE)]

Data_5 <- read.csv("Data/0731_5.csv")  
Year_5 <- Data_5$Year[!is.na(Data_5$Year)]  
Catch_5 <- Data_5$Catch[!is.na(Data_5$Catch)]
CPUE_5 <- Data_5$CPUE[!is.na(Data_5$CPUE)]


TTYear_1  <- length(Year_1)                  
TTCatch_1 <- length(Catch_1)       
TTCPUE_1 <- length(CPUE_1) 

TTYear_2  <- length(Year_2)                  
TTCatch_2 <- length(Catch_2)       
TTCPUE_2 <- length(CPUE_2) 

TTYear_3  <- length(Year_3)                  
TTCatch_3 <- length(Catch_3)       
TTCPUE_3 <- length(CPUE_3) 

TTYear_4  <- length(Year_4)                  
TTCatch_4 <- length(Catch_4)       
TTCPUE_4 <- length(CPUE_4) 

TTYear_5  <- length(Year_5)                  
TTCatch_5 <- length(Catch_5)       
TTCPUE_5 <- length(CPUE_5) 


standata <- list(
  Year_1  = Year_1,
  Year_2  = Year_2,
  Year_3  = Year_3,
  Year_4  = Year_4,
  Year_5  = Year_5,
  Catch_1 = Catch_1,
  Catch_2 = Catch_2,
  Catch_3 = Catch_3,
  Catch_4 = Catch_4,
  Catch_5 = Catch_5,
  CPUE_1 = CPUE_1,
  CPUE_2 = CPUE_2,
  CPUE_3 = CPUE_3,
  CPUE_4 = CPUE_4,
  CPUE_5 = CPUE_5,
  TTYear_1 = TTYear_1,
  TTYear_2 = TTYear_2,
  TTYear_3 = TTYear_3,
  TTYear_4 = TTYear_4,
  TTYear_5 = TTYear_5,
  TTCatch_1 = TTCatch_1,
  TTCatch_2 = TTCatch_2,
  TTCatch_3 = TTCatch_3,
  TTCatch_4 = TTCatch_4,
  TTCatch_5 = TTCatch_5,
  TTCPUE_1 = TTCPUE_1,
  TTCPUE_2 = TTCPUE_2,
  TTCPUE_3 = TTCPUE_3,
  TTCPUE_4 = TTCPUE_4,
  TTCPUE_5 = TTCPUE_5
  )


#chain <- 4; iter <-50000; warmup = 25000; thin=10;(iter-warmup)/thin
chain <- 1; iter <-100; warmup = 10; thin=2; (iter-warmup)/thin

fithrz1 <- stan("Hierarchical_rz_0731.stan",  
               data=standata,
               chain=chain,iter=iter,warmup=warmup,thin=thin,seed=2024,
               control=list(adapt_delta=0.99,max_treedepth=15),
               init=function(){
                 list(r_1    = runif(1,0.5,0.7),
                      r_2    = runif(1,0.5,0.7),
                      r_3    = runif(1,0.5,0.7),
                      r_4    = runif(1,0.5,0.7),
                      r_5    = runif(1,0.5,0.7),
                      r      = runif(1,0.5,0.7),
                      K_1    = runif(1,1000,4500),
                      K_2    = runif(1,1000,4500),
                      K_3    = runif(1,1000,4500),
                      K_4    = runif(1,1000,4500),
                      K_5    = runif(1,1000,4500),
                      D1_1   = runif(1,0.5,1),
                      D1_2   = runif(1,0.5,1),
                      D1_3   = runif(1,0.5,1),
                      D1_4   = runif(1,0.5,1),
                      D1_5   = runif(1,0.5,1),                      
                      shape_1     = runif(1,0.1,2),
                      shape_2     = runif(1,0.1,2),
                      shape_3     = runif(1,0.1,2),
                      shape_4     = runif(1,0.1,2),
                      shape_5     = runif(1,0.1,2),                      
                      shape       = runif(1,0.1,2),
                      tau_1  = runif(1,0.01,0.1),
                      tau_2  = runif(1,0.01,0.1),
                      tau_3  = runif(1,0.01,0.1),
                      tau_4  = runif(1,0.01,0.1),
                      tau_5  = runif(1,0.01,0.1),                      
                      sigmaCPUE_1 = runif(1,0.01,0.3),
                      sigmaCPUE_2 = runif(1,0.01,0.3),
                      sigmaCPUE_3 = runif(1,0.01,0.3),
                      sigmaCPUE_4 = runif(1,0.01,0.3),
                      sigmaCPUE_5 = runif(1,0.01,0.3),                      
                      rsigma = runif(1,0.01,1),
                      zsigma = runif(1,0.01,1),
                      q_1    = runif(1,0.04,0.3),
                      q_2    = runif(1,0.04,0.3),
                      q_3    = runif(1,0.04,0.3),
                      q_4    = runif(1,0.04,0.3),
                      q_5    = runif(1,0.04,0.3),                      
                      B_1  = runif(TTYear_1,1,3000),
                      B_2  = runif(TTYear_2,1,2000),
                      B_3  = runif(TTYear_3,1,1000),
                      B_4  = runif(TTYear_4,1,4000),                      
                      B_5  = runif(TTYear_5,1,1500))
               })
#save(fithrz1, file="fithrz1_0731.Rdata")
#summary(fithrz1)
stan_dens(fithrz1, pars <- c("r_1", "r_2", "r_3", "r_4", "r_5", "r"))
stan_dens(fithrz1, pars <- c("K_1", "K_2", "K_3", "K_4", "K_5"))
stan_dens(fithrz1, pars <- c("D1_1", "D1_2", "D1_3", "D1_4", "D1_5"))
stan_dens(fithrz1, pars <- c("shape_1", "shape_2", "shape_3", "shape_4", "shape_5", "shape"))
stan_dens(fithrz1, pars <- c("tau_1", "tau_2", "tau_3", "tau_4", "tau_5"))
stan_dens(fithrz1, pars <- c("sigmaCPUE_1", "sigmaCPUE_2", "sigmaCPUE_3", "sigmaCPUE_4", "sigmaCPUE_5"))
stan_dens(fithrz1, pars <- c("rsigma", "zsigma"))
stan_dens(fithrz1, pars <- c("q_1", "q_2", "q_3", "q_4", "q_5"))


#pars <- c("r_1", "r_2", "r_3", "r_4", "r_5", "r", "K_1", "K_2", "K_3", "K_4", "K_5", "D1_1", "D1_2", "D1_3", "D1_4", "D1_5", "shape_1", "shape_2", "shape_3", "shape_4", "shape_5", "shape", "tau_1", "tau_2", "tau_3", "tau_4", "tau_5", "sigmaCPUE_1", "sigmaCPUE_2", "sigmaCPUE_3", "sigmaCPUE_4", "sigmaCPUE_5", "rsigma", "zsigma", "q_1", "q_2", "q_3", "q_4", "q_5", "B_1", "B_2", "B_3", "B_4", "B_5")
#traceplot(fithrz1, pars = c("r_R", "r_A", "r_B", "r", "K_R", "K_A", "K_B", "D1_R", "D1_A", "D1_B", "shape_R", "shape_A", "shape_B", "shape", "tau_R", "tau_A", "tau_B", "sigmaCPUE_R", "sigmaCPUE_A", "sigmaCPUE_B", "rsigma", "zsigma", "q_R", "q_A", "q_B"), inc_warmup = F)

#pairs(fit, pars = c("r", "K", "D1", "tau", "sigmaCPUE", "q", "B"))
#library(shinystan)
#launch_shinystan(fit)

fithrz1_array <- as.array(fithrz1)
# 各Chainのみのデータを抽出
fithrz1_chain <- fithrz1_array[, , 1]

hist(log(fithrz1_chain[,]))

load("fithrz1_0731.Rdata")
```